language: java
jdk:
  - oraclejdk8
services:
  - mysql
sudo: false
install: true
before_script: travis_wait 45 mvn install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
script: mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
